version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean 
      - mvn compile 
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
